config/routes.rb
KhanAcademyCorps::Application.routes.draw do
  resources :payment_notifications

  resources :donations
  resources :donation_users
  get 'team' => 'navigation#team', :as => :team
  get 'about' => 'navigation#about', :as => :about
  get 'faq' => 'navigation#faq', :as => :faq
  post 'feedback' => 'feedback#create', :as => :feedback

  root :to => 'donations#index'

end

app/models/donation.rb
class Donation < ActiveRecord::Base
  attr_accessible :amount, :city
  has_many :donation_users
end

app/models/donation_user.rb
class DonationUser < ActiveRecord::Base
  attr_accessible :city, :donation_id, :valid
  validates :city, :presence => true
  belongs_to :donation
  has_one :payment_notification

  before_create :find_or_create_donation

  def paypal_url(return_url, notify_url)
    values = {
      :business => 'sina.z_1337973047_biz@hotmail.com', #Seller's email address
      :cmd => '_donations',
      :upload => 1,
      :return => return_url,
      :currency_code => "CAD",
      :item_name => "The KNetwork Donation",
      :notify_url => notify_url,
      :invoice => id,
      "amount" => 5
    }
    "https://www.sandbox.paypal.com/cgi-bin/webscr?" + values.map{|k,v| "#{k}=#{v}"}.join("&")
  end


  def find_or_create_donation
    donation = Donation.find_or_create_by_city(self.city)
    self.donation = donation
  end
end

app/models/payment_notification.rb
class PaymentNotification < ActiveRecord::Base
  attr_accessible :donation_user_id, :params, :status
  belongs_to :donation_user
  serialize :params
  after_create :mark_donation_as_complete

  private

  def mark_donation_as_complete
    if status == "Completed"
      self.donation_user.update_attribute(:is_valid, true)
      self.donation_user.donation.update_attribute(:amount, self.donation_user.donation.amount + 5)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def current_cart
    if session[:donation_id]
      @current_donation ||= DonationUser.find(session[:donation_id])
      session[:donation_id] = nil if @current_donation.purchased_at
    end
    if session[:donation_id].nil?
      @current_donation = DonationUser.create!
      session[:donation_id] = @current_donation.id
    end
    @current_donation
  end

end

app/controllers/donation_users_controller.rb
class DonationUsersController < ApplicationController


  def create
   # @donation = Donation.new(params[:donation])
    @donation_user = DonationUser.create({
      :city => params[:donation_user][:city]
    })

    session[:user_id] = @donation_user.id
    url = URI.encode(@donation_user.paypal_url(donations_url, payment_notifications_url))
    
    respond_to do |format|
      if @donation_user.save
        format.html { redirect_to url }# root_path, notice: 'Donation was successfully created but not validated.' }
        format.json { render json: @donation_user, status: :created, location: @donation_user }
      else
        format.html { redirect_to root_path  }
        format.json { render json: @donation_user.errors, status: :unprocessable_entity }
      end
    end
  end

end

app/controllers/donations_controller.rb
class DonationsController < ApplicationController
  # GET /donations
  # GET /donations.json
  def index
    @donation_user = DonationUser.new
    @donations = Donation.all
    @top_donations = Donation.order("amount desc").limit(5)
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @donations }
    end
  end

  # GET /donations/1
  # GET /donations/1.json
  def show
    @donation = Donation.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @donation }
    end
  end

  # GET /donations/new
  # GET /donations/new.json
  def new
    @donation = Donation.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @donation }
    end
  end

  # GET /donations/1/edit
  def edit
    @donation = Donation.find(params[:id])
  end

  # POST /donations
  # POST /donations.json
  def create
   # @donation = Donation.new(params[:donation])
     @donation = Donation.find_or_create_by_city({
        :city =>params[:donation][:city], 
        :amount => 0
      })
     @donation.amount = @donation.amount + 5 #params[:donation][:amount].to_f

    respond_to do |format|
      if @donation.save
        format.html { redirect_to donations_path, notice: 'Donation was successfully created.' }
        format.json { render json: @donation, status: :created, location: @donation }
      else
        format.html { redirect_to donations_path  }
        format.json { render json: @donation.errors, status: :unprocessable_entity }
      end
    end

  end

  # PUT /donations/1
  # PUT /donations/1.json
  def update
    @donation = Donation.find(params[:id])

    respond_to do |format|
      if @donation.update_attributes(params[:donation])
        format.html { redirect_to @donation, notice: 'Donation was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @donation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /donations/1
  # DELETE /donations/1.json
  def destroy
    @donation = Donation.find(params[:id])
    @donation.destroy

    respond_to do |format|
      format.html { redirect_to donations_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/feedback_controller.rb
class FeedbackController < ApplicationController
	def create
    if not params[:email].nil?
      UserMailer.send_email(params[:email]).deliver
      redirect_to donations_path, :notice => "Successfuly submitted your feedback. Thank you!"
    end
	end
end

app/controllers/navigation_controller.rb
class NavigationController < ApplicationController

	def team
	end

	def about
	end

	def faq
	end
	
end

app/controllers/payment_notifications_controller.rb
class PaymentNotificationsController < ApplicationController
  # GET /payment_notifications
  # GET /payment_notifications.json
  protect_from_forgery :except => [:create]
  def index
    PaymentNotification.create!(:params => params, :donation_user_id => params[:invoice], :status => params[:payment_status], :transaction_id => params[:txn_id])
    render :nothing => true
  end
  
  def create
    PaymentNotification.create!(:params => params, :donation_user_id => params[:invoice], :status => params[:payment_status], :transaction_id => params[:txn_id])
    render :nothing => true
  end
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/donation_users_helper.rb
module DonationUsersHelper
end

app/helpers/donations_helper.rb
module DonationsHelper
end

app/helpers/payment_notifications_helper.rb
module PaymentNotificationsHelper
end

app/helpers/payments_controller_helper.rb
module PaymentsControllerHelper
end

app/views/donations/edit.html.erb
<h1>Editing donation</h1>

<%= form_for(@donation) do |f| %>
  <% if @donation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@donation.errors.count, "error") %> prohibited this donation from being saved:</h2>

      <ul>
      <% @donation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br />
    <%= f.text_field :state %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>


<%= link_to 'Show', @donation %> |
<%= link_to 'Back', donations_path %>

app/views/donations/index.html.erb
<%= content_tag "div", "", {:id => "donations", :data => { :donation => @top_donations.to_json }} %>

<div class="main_body">
  <div class="main_leftside">
    <p class="main_left_header">
        DELIVERING A FREE WORLD CLASS EDUCATION -<span> TO YOUR COMMUNITY</span>
    </p><hr />
    <p class="main_left_body">
      Your donation shows “money where your mouth is” 
      support for bringing Khan Academy to a specific 
      location – We keep track of location-based 
      supporter totals
      <br /><br />
      The more supporters a location has, the more 
      evidence (and resources) local volunteers and local 
      champions will have indicating that local schools 
      and school systems should incorporate Khan 
      Academy into the curriculum.
    </p>

  </div>
  <div class="main_rightside">
    <%= form_for(@donation_user) do |f| %>
      <div class="field">
        <div class="location">
          <%= f.label :location %>
        </div>
        <div class="city">
          <%= f.text_field :city %>
        </div>
      </div>
      <div class="actionFAQ">
        <div class="actions">
          <div class="donate">Donate</div>
            <%= f.submit :class => "donate_button", :value => "$5"%>
          </div>
        
        <div class="faq-link">
          <p>why only<span> $5</span>. <%=link_to "Find Out", faq_path(:donations => true) + "#donations" %></p>
        </div>
      </div>      
    <% end %>

    <p class="explanation">
      Your donation goes directly to Khan Academy, a 
      tax-exempt 501(C)3 nonprot organization (TAX ID 
      Number: 26-1544963). Your gift is tax-deductible.
    </p>
  </div>
</div>

<%= stylesheet_link_tag "donations.css" %>

<div class="graph">
  <p class="above-graph"> Project #1 efforts is to 
  <span> bring Khan Academy into the classroom </span> (100% free for all users)
  </p>
  <h3>LEADERBOARD FOR COMMUNITY SUPPORT</h3><hr />
  <div id="position">
  </div>
  <div id="cities">
  </div>
  <div id="amount">
  </div>
  <div id="chart_place">
  </div>
</div>

app/views/donations/show.html.erb
<p id="notice"><%= notice %></p>
 <p>
  <b>City:</b>
  <%= @donation.city %>
</p>

<p>
  <b>State:</b>
  <%= @donation.state %>
</p>

<p>
  <b>Country:</b>
  <%= @donation.country %>
</p>

<p>
  <b>Amount:</b>
  <%= @donation.amount %>
</p>


<%= link_to 'Edit', edit_donation_path(@donation) %> |
<%= link_to 'Back', donations_path %>

app/views/feedback/feedback.html.erb
asdlfkjasdlfkj

app/views/layouts/application.html.erb
<div id="comments">
  <div id="close_button">&nbsp;</div>
  <form id="user_input_comment" action="<%= feedback_path %>" method="POST">
    <label>Name: </label> <br />
    <input type="text"  name="email[name]"/><br />
    <label>Email: </label> <br />
    <input type="text"  name="email[email]"/><br />
    <label>Comments: </label> <br />
    <textarea rows="4" cols="30" name="email[comment]"></textarea><br />
    <input type="submit" value="Submit" id="submit"/>
  </form>
</div>

<!DOCTYPE html>
<html>
<head>
  <title>K-NetworkDonations</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="container">
    <div class="header">
      <a href="/team" class="team <%= 'active' if params[:action] == "team"%>">TEAM</a>
      <a href="/donations" class="donations <%= 'active' if params[:action] == "index"%>">HOME</a>
      <a href="/about" class="about <%= 'active' if params[:action] == "about"%>">ABOUT</a>
      <a href="/faq" class="faq <%= 'active' if params[:action] == "faq"%>">FAQ</a>
    </div>

    <p class="slogan"> <span>EMPOWERING YOU</span> TO BRING INNOVATION TO YOUR SCHOOL </p> 

    <div id="content">
      <%= yield %>
    </div>

    <div class="footer">
      <div class="comments">
        <p><span>Questions,comments & suggestions</span> to help make this site better
        </p>
      </div>
    </div>
  </div>
</body>
</html>

app/views/navigation/about.html.erb
<%= stylesheet_link_tag "about.css" %>

<div class="about-body">
	<p class="about-header">About</p><hr>
	<div class="about-leftside">
		<p><span>About The K Network</span></p>
		<p> The K Network is a 501(c)3 non-profit with the mission to empower learners worldwide to take control of their education – for free. The K Network is hosting The Knowledge Corps Initiative.
		</p>
		<p><span>About The Knowledge Corps</span></p>
		<p>The Knowledge Corps is an initiative to allow communities to raise money and create local mandates to bring innovation to local schools and school systems. People “vote” with a small donation and their location / their school / their school district. This system creates a “money where your mouth is” petition for innovative education initiatives.
		</p>
	</div>
	<div class="about-rightside">
		<p><span> About Project #1: Bring Khan Academy into the class-room</span></p>
		<p>Knowledge Corps initiatives must be 100% free for all schools, teachers, parents and students. Khan Academy meets this requirement. By raising money for a school or school district, community members are opening up the possibility of using this money for Project #1. The money may also be kept as resources available for future projects.
		</p>
		<p>More detailed info on Project #1 is in the <%= link_to "FAQ", faq_path(:projects => true) + "#projects" %>.
		</p>
		<p><span>About Project #2 and future projects</span></p>
		<p>	Knowledge Corps users can find projects and add
			them to the list of possible uses for monies raised for
			a community. The Knowledge Corps will maintain a
			list of these projects. In the future, as the website
			and the user base evolves, it may be possible to more
			clearly tie dollars donated to a specific project. The
			Knowledge Corps is in alpha right now.
		</p>
	</div>
</div>

app/views/navigation/faq.html.erb
<%= stylesheet_link_tag "faq.css" %>
<div class="faq-body">
	<a name="donations">&nbsp;</a>
	<% if params[:donations] != nil then %>
		<p class="faq-header">FAQ on<span> Donations</span><span class="expander" id="expand-donations"> [-] </span></p>
	<% else %>
		<p class="faq-header">FAQ on<span> Donations</span><span class="expander" id="expand-donations"> [+] </span></p>
	<% end %>
	<hr />
	<div class="faq-donations <%= 'show' if params[:donations] != nil%>">
		<div class="faq-leftside">
			<p><span>What will happen to my donation of $5?</span></p>
			<p>It will go into in a Paypal account registered to The K
			Network, a 501(c)3 non-profit. It will sit there
			unspent until there is a mandate for the use of those
			resources.
			</p>
			<p>Your $5 donation will be linked to your location, and
			totals of all the locations will be listed. So if there is
			grassroots support for this kind of initiative in a
			single location, people will be connected and
			resources will be collected.
			</p>
			<p>In addition, The Knowledge Corps will also be keep-
			ing track of the collected resources of a larger geog-
			raphy, say a school district, a county, or a state /
			province. This will allow the larger community of
			people to pool “money where your mouth is”
			resources to encourage larger top-down change. We
			don’t anticipate any results from this in the first 12-18
			months of this project, but it is one of the stated
			goals. You are donating to both a local cause and
			also a larger initiative for change.
			</p>

			<p><span>What if minimum funding levels for my school / city / school district are not met?</span></p>
			<p>Some fundraising websites are one project = one source of funds, go or no go with a deadline (e.g. 30, 45, 90 days). The Knowledge Corps is different. We are a platform to develop community support for bringing innovation to your school. This may take months or years, depending on all the stakeholders involved in the process. But every time $5 is donated and one more “money where your mouth is” person joins the Corps, the support for education innovation in that community goes up.
			</p>
			<p> Some locations may take off like a rocket and reach-
			ing funding levels within days, weeks or months.
			Others may be a slow burn. So if a minimum funding
			level is not met, the money sits and grows, indefi-
			nitely, until such a time where minimum funding
			levels are met.
			</p>
		</div>

		<div class="faq-rightside">
			<p><span>Is there any way of getting my money back?</span></p>
			<p>Yes. All members of The Corps can request to have
			their money sent back at any time. As of today you
			will have to email thecorps@theknetwork.org. In the
			near future, each member of The Corps will have a
			“My Account” page where you can request this more easily.
			</p>
			<p><span>Is my donation tax-deductible?</span></p>
			<p>Your donation is a 100% tax deductible donation to a
			501(c) non-profit for which you get immediate tax
			benefits. In addition to those tax benefits, you may
			get other benefits (e.g. reaching a funding level and
			having services delivered to your school or commu-
			nity). But in effect you are donating to a general pool
			of funds from which benefits will be conferred, not
			pledging funds to a specific project which will be
			paid for by those donations.
			</p>
			<p>Note: This structure may change in the future, but
			this is how it exists today.
			</p>
			<p><span>Is this is a legitimate and “positive benefit for the community” good-faith effort?</span></p>
			<p>The K Network is a registered 501(c)3 non-profit with
			tax ID 45-5167493. The K Network is spending tens of
			thousands of dollars a month building a platform for
			social and peer to peer teaching and learning. Our
			existing web-based software turns Khan Academy
			from a single person experience (learn the material
			by yourself ) into a Group learning experience – you
			can create a team and conquer the Khan knowledge
			map with other people, bringing all the positive
			group dynamics of being on a soccer team... into the Khan Academy experience.
			</p>
			<p>So yes, The K Network is a bona-fide non-profit. The Knowledge Corps is a division of The K Network to allow us to reach out to and start building relationships with communities, potential users, influencers in educations, and finally people who want to support education innovation, both small and large. We want to build these relationships to accomplish our larger goals and deliver on The K Network’s mission which is to empower learners worldwide to take control of their education for free.
			</p>
		</div>
	</div>
	<div class="clear"></div>
	<a name="projects">&nbsp;</a>
	<% if params[:projects] != nil then %>
		<p class="faq-header">FAQ on<span> Projects</span><span class="expander" id="expand-projects"> [-] </span></p>
	<% else %>
		<p class="faq-header">FAQ on<span> Projects</span><span class="expander" id="expand-projects"> [+] </span></p>
	<% end %>
	<hr />
	<div class="faq-projects <%= 'show' if params[:projects] != nil%>">
		<div class="faq-leftside">
			<p><span>What are the donations being used for?</span></p>
			<p>The Knowledge Corps currently has one project for donations: Project #1. As The Knowledge Corps grows and develops a wider user base, more projects will be added.
			</p>
			<p><span>What is Project #1?</span></p>
			<p>Project #1 is to bring Khan Academy into your class-
			room, school or school district. For funding levels of
			$500, $1250, and $4000, a “Khan in the classroom”
			expert will work with 1 teacher, a group of up to 5
			teachers or an entire school respectively to under-
			stand better how to implement Khan Academy in the
			classroom.
			</p>
		</div>
		<div class="faq-rightside">
			<p><span>What about other levels of funding or individual or unique situations?
			</span></p>
			<p>The Knowledge Corps is about delivering happiness to its members, so if you have a suggestion for how to use funds for Project #1, e.g. for entire school districts or homeschooling situations, please email us and we will find a win-win solution.
			</p>
			<p><span>Who are the “Khan in the classroom” experts?</span></p>
			<p>Right now we have one expert, Harsh Patel. His bio is on the<a href="/about"> About</a> page.</p>
			<p>Can I just hire Harsh directly and bypass this donation / community support system?</p>
			<p>Yes, if you have school and teacher buy-in and have secured the funding, you can bring on Harsh directly.</p>
		</div>
	</div>
	<div class="clear"></div>
	<a name="support">&nbsp;</a>
	<p class="faq-header">FAQ on<span> School buy-in / Support</span><span class="expander" id="expand-support"> [+] </span></p><hr>
	<div class="faq-support">
		<div class="faq-leftside">
			<p><span>What if we have reached a funding goal but the local school does not want Project #1 / Khan Academy?</span></p>
			<p>The money will sit unspent and irrevocably con- 
			nected to your location until a suitable project is 
			agreed upon by all stakeholders and there is buy-in 
			from all sides. 
			</p>
			<p><span>Why not use the Kickstarter model of one project = one source of funds, go or no go?</span></p>
			<p>Currently, there is no vehicle to allow interested
			parents, students and community members to vote
			or have the resources to advance innovation in their
			local school system. The Knowledge Corps is that
			vehicle.
			</p>
			<p>The Kickstarter model doesn’t work here because The Knowledge Corps is trying to accomplish two things:
			</p>
			<p>A) Finding resources for implementation
			</p>
			<p>B) Building grassroots support to encourage buy-in from schools and districts
			</p>
			<p>In Kickstarter projects, all parties already have buy-in. The filmmaker wants the film to be made. The video game company is ready to make the game. The
			</p>
		</div>
		<div class="faq-rightside">
			<p>digital watch company is prepared to build 85,000 watches.</p>
			<p>With innovation-based initiatives for schools and
			school district, in some cases there is an inherent
			resistance to change, and in other cases there needs
			to be validation before the decision maker (e.g. the
			school, district or province / state) signs off.
			</p>
			<p>Thus, the idea of the Knowledge Corps is that in
			addition to simply finding the resources a la Kick-
			starter, something else must happen: buy-in from all
			the stakeholders.
			</p>
			<p>Having Corps members make a $5 donation is the
			difference between a simply signing a petition and a
			creating a “money where your mouth is” petition. The Knowledge Corps will allow the community to have more of a say in the innovation decisions by a school or school district.
			</p>
			<p>Because of this structure, this process may happen quickly or it may take months or even years. But as more and more people in a single geography join the Corps and donate $5, both the resources available and the grassroots support will go up, increasing the chance that there will be movement and projects will be implemented.
			</p>
		</div>
	</div>
	<div class="clear"></div>
	<a name="interested">&nbsp;</a>	
	<p class="faq-header">FAQ on<span> “I’m an interested parent / student / teacher”</span><span class="expander" id="expand-interested"> [+] </span></p><hr>
	<div class="faq-interested">
		<div class="faq-leftside">
			<p><span>I’m an interested parent – what can I do?</span></p>
			<p>As a parent, you can both join the Corps with a $5
			donation and spread the word to build support in
			your local community (and to friends in other com-
			munities).
			</p>
			<p><span>I’m an interested student – what can I do?</span></p>
			<p>As a student, you can both join the Corps with a $5
			donation and spread the word to build support in
			your local community (and to friends in other com-
			munities).
			</p>
			<p><span>I’m an interested teacher – what can I do?</span></p>
			<p>As a teacher, you can both join the Corps with a $5
			donation and spread the word to build support in
			your local community (and to friends in other com-
			</p>	
		</div>
		<div class="faq-rightside">
			<p>munities). You can also let us know via email if you,
			your school or your district are open to benefitting
			from Project #1 (Bringing Khan Academy into the
			classroom) at thecorps@theknetwork.org.
			</p>
			<p><span>I’m an interested school administrator – what can I do?</span></p>
			<p>As an administrator, you can both join the Corps with
			a $5 donation and spread the word to build support
			in your local community (and to friends in other
			communities). You can also let us know via email if
			your school or your district are open to benefitting
			from Project #1 (Bringing Khan Academy into the
			classroom) at thecorps@theknetwork.org.
			</p>
		</div>
	</div>
</div>

app/views/payment_notifications/_form.html.erb
<%= form_for(@payment_notification) do |f| %>
  <% if @payment_notification.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@payment_notification.errors.count, "error") %> prohibited this payment_notification from being saved:</h2>

      <ul>
      <% @payment_notification.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :params %><br />
    <%= f.text_area :params %>
  </div>
  <div class="field">
    <%= f.label :donation_id %><br />
    <%= f.number_field :donation_id %>
  </div>
  <div class="field">
    <%= f.label :status %><br />
    <%= f.text_field :status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/payment_notifications/edit.html.erb
<h1>Editing payment_notification</h1>

<%= render 'form' %>

<%= link_to 'Show', @payment_notification %> |
<%= link_to 'Back', payment_notifications_path %>

app/views/payment_notifications/index.html.erb
<h1>Listing payment_notifications</h1>

<table>
  <tr>
    <th>Params</th>
    <th>Donation</th>
    <th>Status</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @payment_notifications.each do |payment_notification| %>
  <tr>
    <td><%= payment_notification.params %></td>
    <td><%= payment_notification.donation_id %></td>
    <td><%= payment_notification.status %></td>
    <td><%= link_to 'Show', payment_notification %></td>
    <td><%= link_to 'Edit', edit_payment_notification_path(payment_notification) %></td>
    <td><%= link_to 'Destroy', payment_notification, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Payment notification', new_payment_notification_path %>

app/views/payment_notifications/new.html.erb
<h1>New payment_notification</h1>

<%= render 'form' %>

<%= link_to 'Back', payment_notifications_path %>

app/views/payment_notifications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Params:</b>
  <%= @payment_notification.params %>
</p>

<p>
  <b>Donation:</b>
  <%= @payment_notification.donation_id %>
</p>

<p>
  <b>Status:</b>
  <%= @payment_notification.status %>
</p>


<%= link_to 'Edit', edit_payment_notification_path(@payment_notification) %> |
<%= link_to 'Back', payment_notifications_path %>